### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [ClickTripz/ctz-tag-template-gtm#1]
https://github.com/ClickTripz/ctz-tag-template-gtm/blob/ff393654572fff403e44bd665d1d53ead0d1ad14/template.tpl#L45

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by nicholasvrdoljak** [comment]
https://github.com/ClickTripz/ctz-tag-template-gtm/blob/master/template.tpl#L45
Thank you, it has been updated.
